# Generated by Django 3.2 on 2024-08-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctable',
            name='doc_file',
            field=models.FileField(upload_to='doc_templates/'),
        ),
    ]
